Standardized TAP file name
adoptium/TKG pull request #241
Opened 2021-10-05 20:40 UTC by amandanguyeen

Fixes #236 

Format is now: Test_openjdk<JDK VERSION>_<JDK IMPL>_<TESTTARGET>_<SPEC>.tap
Signed-off-by: Amanda Nguyen <amanda6@ualberta.ca>

2021-10-05 20:42 UTC, amandanguyeen commented
I saw that there was another variable called CUSTOM_TARGET but assumed that the target we wanted was test target.

2021-10-06 14:03 UTC, llxia commented
Thanks @amandanguyeen . Yes, we do not need to worry about CUSTOM_TARGET. However, there are a few cases that we need to take care of:
- TARGET can be a list of tests. i.e.,  `testList TESTLIST=jit_jitt,jit_recognizedMethod_1,testSCCMLTests2_1`. When this happens, we should use `testList` in the TAP filename (instead of the value of TARGET). i.e., Test_openjdk17_hotspot_testList_x86-64_mac.tap
- we need to use PLATFORM, not SPEC. That is, x86-64_mac for macos
- user should be able to set TAP file name if needed

2021-10-19 16:21 UTC, llxia commented
@amandanguyeen is this ready for review?

2021-10-19 18:05 UTC, llxia requested changes

2021-10-20 16:19 UTC, amandanguyeen commented on scripts/resultsSum.pl
> +		my $userTapInput = $splitTapFile[-1];
If the tap name is not set then userTapInput will be an empty string which gets handled in the if statement below
Definitely like the idea of having two variables vs splitting, will update!

2021-10-20 16:20 UTC, amandanguyeen commented on settings.mk
> +	export TAP_NAME:=$(TAP_NAME).tap
from what I understand I thought a user would have to do something like `export TAP_NAME=blah` in order to set the tap name no?

2021-11-01 14:41 UTC, merged