Added getTestenvProperties
adoptium/TKG pull request #248
Opened 2021-11-10 02:49 UTC by psaunderualberta

Reference to (this)[https://github.com/adoptium/aqa-tests/pull/3096] PR. This script belongs alongside getSHA.sh since it performs near-identical functions.

2021-11-15 21:55 UTC, llxia requested changes

2021-11-15 21:55 UTC, llxia commented on scripts/build_test.xml
> +				<arg line="--output_file ${TEST_ROOT}/TKG/testenv.properties" />
The path is wrong. We need to output under `testenv`

2021-11-25 13:51 UTC, llxia approved these changes
LGTM

2021-11-25 15:41 UTC, smlambert approved these changes
LGTM

2021-11-25 15:43 UTC, merged