Update test result regex for all tests failed
adoptium/TKG pull request #397
Opened 2023-01-27 22:27 UTC by sophia-guo

Support cases that all tests failed with the summary of failed only - Test results: failed: **

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

2023-01-27 22:54 UTC, sophia-guo commented
Grinder on windows with all tests failed: https://ci.adoptopenjdk.net/job/Grinder/6499/artifact/aqa-tests/TKG/output_16748596686978/Grinder_20230127224441.tap/*view*/ with 

```
      Test results: failed: 3
    duration_ms: 82089
```

2023-01-28 16:31 UTC, sophia-guo commented
Grinder on Mac with passed and failed test cases https://ci.adoptopenjdk.net/job/Grinder/6503/artifact/aqa-tests/TKG/output_16748806757558/Grinder_20230128043557.tap/*view*/

2023-01-30 18:34 UTC, renfeiw approved these changes
LGTM

2023-01-30 18:43 UTC, karianna requested changes

2023-01-30 18:43 UTC, karianna commented on scripts/resultsSum.pl
> +									#	if ( ($lines[$i+1] =~ /(TEST: )(.*?)(\.java|\.sh)$/) || ($lines[$i+1] =~ /(Test results: passed: )(\d{1,}; .*\d{1,}$)/) || ($lines[$i+1] =~ /(Test results: failed: )(.*\d{1,}$)/)) {
Commented out code?  Remove?

2023-01-30 19:20 UTC, sophia-guo commented on scripts/resultsSum.pl
> +									#	if ( ($lines[$i+1] =~ /(TEST: )(.*?)(\.java|\.sh)$/) || ($lines[$i+1] =~ /(Test results: passed: )(\d{1,}; .*\d{1,}$)/) || ($lines[$i+1] =~ /(Test results: failed: )(.*\d{1,}$)/)) {
Removed.

2023-01-30 23:19 UTC, karianna approved these changes

2023-01-30 23:20 UTC, merged