Move getJtreg into getDependencies
adoptium/TKG pull request #473
Opened 2023-11-15 21:09 UTC by annaibm

-Moved the getJtreg version download logic into TKG/scripts/getDependencies.xml

resolves : https://github.com/adoptium/aqa-tests/issues/4848

2023-11-15 21:09 UTC, annaibm commented
Grinder outputs:
openjdk: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36142/
Crypto test: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36150/
ssl-test:https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36151

2023-11-17 18:55 UTC, llxia requested changes

2023-11-17 18:55 UTC, llxia commented on scripts/getDependencies.xml
> +		</ant> -->
remove the above lines

2023-11-17 18:55 UTC, llxia commented on scripts/getDependencies.xml
> +		</fail>
Please use the original logic https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L44-L67

2023-11-17 18:55 UTC, llxia commented on scripts/getDependencies.xml
> +		</condition>
Please use the original logic

2023-11-17 18:55 UTC, llxia commented on scripts/getDependencies.xml
> +		<echo>JDK_VERSION  is ${JDK_VERSION}</echo>
Please remove the debugging messages

2023-11-17 19:58 UTC, annaibm commented
Made requested changes. Kindly review.
Grinder outputs:
openjdk: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36177/ (36178)
Crypto test: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36180/
ssl-test:https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36181

2023-11-21 21:56 UTC, llxia commented on scripts/getDependencies.xml
> +   <target name="getJtregVersion">
Please fix indentation

2023-11-22 20:44 UTC, annaibm commented
Grinder outputs:
openjdk: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36330/
openjdk with hotspot: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36373/
Crypto test: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36331/
ssl-test:https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36332/

2023-11-22 20:50 UTC, llxia commented on scripts/getDependencies.xml
> +		<!-- Call the getJtreg target with the LIB parameter -->
Can we remove the comment?

2023-11-22 20:51 UTC, annaibm commented on scripts/getDependencies.xml
> +		<!-- Call the getJtreg target with the LIB parameter -->
Is it the comment on line 63?

2023-11-22 20:58 UTC, llxia commented on scripts/getDependencies.xml
> +		<!-- Call the getJtreg target with the LIB parameter -->
yes

2023-11-22 21:14 UTC, llxia approved these changes
LGTM

2023-11-22 22:19 UTC, karianna approved these changes

2023-11-23 19:38 UTC, merged