Removed view/Dependencies from asmtools URL
adoptium/TKG pull request #643
Opened 2024-11-28 01:20 UTC by IamLRBA

As per the issue [546](https://github.com/adoptium/TKG/issues/546)
cc
@llxia 
@smlambert

2024-11-28 15:14 UTC, llxia commented
Thanks @IamLRBA . Please remove your unrelated local changes

![image](https://github.com/user-attachments/assets/5d4b73a7-e849-44b3-8f76-89489e3ba335)

2024-11-28 15:15 UTC, llxia requested changes
See https://github.com/adoptium/TKG/pull/643#issuecomment-2506342743

2024-11-28 15:16 UTC, llxia commented on scripts/getDependencies.pl
> +        url => 'https://ci.adoptium.net/job/dependency_pipeline/lastSuccessfulBuild/artifact/asmtools/asmtools-core-7.0.b10-ea.jar',
Please fix the indentation. The original code is correct.

2024-11-28 22:36 UTC, closed without merging

2024-11-29 00:06 UTC, IamLRBA commented
I have created a new [PR](https://github.com/adoptium/TKG/compare/master...IamLRBA:TKG:master) that should have the corrections addressed. You could look at it.
Thank You!